api_platform:
    defaults:
      cache_headers:
          etag: true

          # Default value for the response max age.
          max_age: 0

          # Default value for the response shared (proxy) max age.
          shared_max_age: 0

    allow_plain_identifiers: true
    mapping:
        paths: ['%kernel.project_dir%/src/Entity', '%kernel.project_dir%/src/Document']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
